name: test github action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  Integration-Tests:
    runs-on: "ubuntu-latest"

    container:
      image: rocm/rocm-terminal:5.5
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prerequisite
        run: |
          set -x
          du -h -d 1 / || true
          df -h || true
          apt update
          apt install -y libpython3-dev python3-pip
          du -h -d 1 / || true
          df -h || true

      - name: Install pytorch
        run: |
          pip3 --version
          python3 -m pip install torch==1.13.1 --index-url https://download.pytorch.org/whl/rocm5.2&
          while ps $! > /dev/null; do sleep 1; df -h | grep  "/$"; done
          du -h -d 1 / || true
          df -h || true

